const fs = require('fs');
const path = require('path');

const basePath = path.join(__dirname, 'src', 'app', 'dashboard', 'finance');

const workspacesConfig = {
  'student-billing': {
    title: 'Student Billing',
    description: 'Manage fee structures, generate invoices, and handle student balances.',
    tabs: ['fee-structures', 'billing', 'discounts-waivers', 'debtors']
  },
  'payments-receipts': {
    title: 'Payments & Receipts',
    description: 'Process incoming payments, issue receipts, and allocate funds.',
    tabs: ['collections', 'receipts', 'allocation', 'reconciliation']
  },
  'accounting': {
    title: 'Accounting',
    description: 'Full double-entry accounting, ledgers, payables, and receivables.',
    tabs: ['general-ledger', 'accounts-receivable', 'accounts-payable', 'fixed-assets', 'financial-year']
  },
  'banking-cash': {
    title: 'Banking & Cash',
    description: 'Manage bank accounts, petty cash, and bank reconciliations.',
    tabs: ['banks', 'cash-management', 'reconciliation']
  },
  'budgeting': {
    title: 'Budgeting',
    description: 'Plan, monitor, and forecast school budgets.',
    tabs: ['budgets', 'monitoring']
  },
  'financial-reports': {
    title: 'Financial Reports',
    description: 'Generate standard accounting, management, and compliance reports.',
    tabs: ['standard', 'school-reports', 'management', 'compliance']
  }
};

const pagesData = {
  // Student Billing
  'fee-structures': { title: 'Fee Structures', cols: ['Structure Name', 'Applicable Classes', 'Total Amount', 'Status'], actions: ['New Structure'], hasAI: false },
  'billing': { title: 'Student Billing', cols: ['Invoice No', 'Student Name', 'Class', 'Amount', 'Due Date', 'Status'], actions: ['Generate Invoices'], hasAI: false },
  'discounts-waivers': { title: 'Discounts & Waivers', cols: ['Student Name', 'Type', 'Amount/Percentage', 'Approved By', 'Status'], actions: ['Add Discount'], hasAI: false },
  'debtors': { title: 'Debtors', cols: ['Student Name', 'Parent Contact', 'Outstanding Balance', 'Days Overdue', 'AI Risk Level'], actions: ['AI Predict Defaults', 'Send Reminders'], hasAI: true },

  // Payments & Receipts
  'collections': { title: 'Collections', cols: ['Transaction ID', 'Date', 'Method', 'Reference', 'Amount', 'Status'], actions: ['New Payment'], hasAI: false },
  'receipts': { title: 'Receipts', cols: ['Receipt No', 'Payer', 'Date', 'Amount', 'Status'], actions: ['Issue Receipt'], hasAI: false },
  'allocation': { title: 'Payment Allocation', cols: ['Receipt No', 'Student', 'Unallocated Amount', 'Status'], actions: ['Auto-Allocate'], hasAI: false },
  'reconciliation': { title: 'M-Pesa / Card Reconciliation', cols: ['Gateway', 'Date', 'Total Transactions', 'Matched', 'Status'], actions: ['Run Reconciliation'], hasAI: false },

  // Accounting
  'general-ledger': { title: 'General Ledger', cols: ['Account Code', 'Account Name', 'Type', 'Debit', 'Credit', 'Balance'], actions: ['Add Journal Entry'], hasAI: false },
  'accounts-receivable': { title: 'Accounts Receivable', cols: ['Customer', 'Invoice No', 'Date', 'Amount', 'Status'], actions: ['New Invoice'], hasAI: false },
  'accounts-payable': { title: 'Accounts Payable', cols: ['Supplier', 'Bill No', 'Date', 'Amount Due', 'Status'], actions: ['Enter Bill'], hasAI: false },
  'fixed-assets': { title: 'Fixed Assets', cols: ['Asset ID', 'Name', 'Purchase Value', 'Current Value', 'Depreciation', 'Status'], actions: ['Register Asset'], hasAI: false },
  'financial-year': { title: 'Financial Year', cols: ['Period', 'Start Date', 'End Date', 'Status'], actions: ['Close Period'], hasAI: false },

  // Banking & Cash
  'banks': { title: 'Bank Accounts', cols: ['Bank Name', 'Account No', 'Currency', 'Current Balance', 'Status'], actions: ['Add Account'], hasAI: false },
  'cash-management': { title: 'Cash Management', cols: ['Register/Petty Cash', 'Custodian', 'Opening Bal', 'Closing Bal', 'Status'], actions: ['Cash Transfer'], hasAI: false },
  'reconciliation': { title: 'Bank Reconciliation', cols: ['Account', 'Statement Date', 'System Balance', 'Statement Balance', 'Difference'], actions: ['AI Auto-Match', 'Upload Statement'], hasAI: true },

  // Budgeting
  'budgets': { title: 'Budgets', cols: ['Department', 'Annual Budget', 'Utilized', 'Remaining', 'Status'], actions: ['New Budget'], hasAI: false },
  'monitoring': { title: 'Budget Monitoring', cols: ['Category', 'Budgeted', 'Actual', 'Variance', 'AI Forecast'], actions: ['AI Suggest Adjustments', 'Generate Report'], hasAI: true },

  // Financial Reports
  'standard': { title: 'Standard Accounting Reports', cols: ['Report Name', 'Period', 'Generated By', 'Date', 'Status'], actions: ['Generate Statement'], hasAI: false },
  'school-reports': { title: 'School Financial Reports', cols: ['Report Type', 'Date Range', 'Target Audience', 'Status'], actions: ['Generate Report'], hasAI: false },
  'management': { title: 'Management Reports', cols: ['Report Name', 'Department', 'Date Generated', 'Status'], actions: ['Generate Report'], hasAI: false },
  'compliance': { title: 'Compliance & Audit', cols: ['Requirement', 'Due Date', 'Filing Status', 'Auditor'], actions: ['Upload Document'], hasAI: false }
};

const defaultData = [
  { id: '1001', col1: 'Data A', col2: 'Data B', col3: 'Data C', col4: 'Data D', status: 'Paid' },
  { id: '1002', col1: 'Data X', col2: 'Data Y', col3: 'Data Z', col4: 'Data W', status: 'Pending' },
  { id: '1003', col1: 'Data M', col2: 'Data N', col3: 'Data O', col4: 'Data P', status: 'Overdue' },
  { id: '1004', col1: 'Data Q', col2: 'Data R', col3: 'Data S', col4: 'Data T', status: 'Draft' },
];

for (const [workspace, config] of Object.entries(workspacesConfig)) {
  const workspacePath = path.join(basePath, workspace);
  fs.mkdirSync(workspacePath, { recursive: true });

  // Create layout with the new Pill-style tabs and Page Header
  const layoutContent = `"use client";
import React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Download, Filter, Search } from "lucide-react";

export default function WorkspaceLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  
  const tabs = [
${config.tabs.map(t => `    { name: "${t.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}", href: "/dashboard/finance/${workspace}/${t}" }`).join(',\n')}
  ];

  return (
    <div className="max-w-7xl mx-auto space-y-6 pb-12">
      {/* Consistent Page Header */}
      <div className="mb-6 flex flex-col md:flex-row md:items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-800 capitalize">
            ${config.title}
          </h1>
          <p className="text-slate-500 mt-1">
            ${config.description}
          </p>
        </div>
        
        {/* Global Toolbar for Workspace */}
        <div className="flex items-center gap-3">
          <div className="relative hidden sm:block">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input 
              type="text" 
              placeholder="Search in ${config.title}..." 
              className="pl-9 pr-4 py-2 text-sm bg-white border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
            />
          </div>
          <button className="flex items-center gap-2 px-3 py-2 text-sm font-bold text-primary-700 bg-white border border-primary-200 rounded-lg hover:bg-primary-50 transition-colors">
            <Filter className="w-4 h-4" />
            Filter
          </button>
          <button className="flex items-center gap-2 px-3 py-2 text-sm font-bold text-primary-700 bg-white border border-primary-200 rounded-lg hover:bg-primary-50 transition-colors">
            <Download className="w-4 h-4" />
            Export
          </button>
        </div>
      </div>

      {/* Pill-style Navigation */}
      <div className="overflow-x-auto pb-2">
        <nav className="flex space-x-2 min-w-max" aria-label="Tabs">
          {tabs.map((tab) => {
            const isActive = pathname === tab.href || pathname.startsWith(tab.href + '/');
            return (
              <Link
                key={tab.name}
                href={tab.href}
                className={\`
                  whitespace-nowrap px-4 py-2 text-sm font-semibold rounded-full transition-colors
                  \${isActive 
                    ? 'bg-primary-900/10 text-primary-900' 
                    : 'text-slate-500 hover:text-slate-700 hover:bg-slate-100'
                  }
                \`}
              >
                {tab.name}
              </Link>
            );
          })}
        </nav>
      </div>

      {/* Content Area */}
      <div className="mt-4">
        {children}
      </div>
    </div>
  );
}`;
  fs.writeFileSync(path.join(workspacePath, 'layout.tsx'), layoutContent);

  // Redirect base to first tab
  const basePageContent = `import { redirect } from 'next/navigation';
export default function Page() {
  redirect('/dashboard/finance/${workspace}/${config.tabs[0]}');
}`;
  fs.writeFileSync(path.join(workspacePath, 'page.tsx'), basePageContent);

  // Create tabs
  for (const tab of config.tabs) {
    const tabPath = path.join(workspacePath, tab);
    fs.mkdirSync(tabPath, { recursive: true });

    const pageDef = pagesData[tab] || { title: tab, cols: ['Col1', 'Col2', 'Col3', 'Col4', 'Status'], actions: ['Add New'], hasAI: false };

    // Primary: Solid Purple. Secondary: White with Purple Border.
    const actionButtons = pageDef.actions.map((act, i) => {
      const isAiAction = act.startsWith('AI ');
      if (isAiAction) {
        return '<button className="flex items-center gap-2 px-4 py-2 text-sm font-bold text-white bg-gradient-to-r from-purple-600 to-indigo-600 rounded-lg hover:from-purple-700 hover:to-indigo-700 transition-colors shadow-sm"><Sparkles className="w-4 h-4 text-purple-200" />' + act + '</button>';
      } else if (i === 0) {
        return '<button className="flex items-center gap-2 px-4 py-2 text-sm font-bold text-white bg-primary-900 rounded-lg hover:bg-primary-800 transition-colors shadow-sm"><Plus className="w-4 h-4" />' + act + '</button>';
      } else {
        return '<button className="flex items-center gap-2 px-3 py-2 text-sm font-bold text-primary-700 bg-white border border-primary-200 rounded-lg hover:bg-primary-50 transition-colors">' + act + '</button>';
      }
    }).join('\n          ');

    const tableHeaders = pageDef.cols.map(col => '<th className="px-6 py-4">' + col + '</th>').join('\n              ');

    const code = `import React from "react";
import { Plus, MoreHorizontal, Sparkles } from "lucide-react";

const mockData = ${JSON.stringify(defaultData, null, 2)};

export default function ${tab.replace(/-/g, '').charAt(0).toUpperCase() + tab.replace(/-/g, '').slice(1)}Page() {
  return (
    <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden flex flex-col min-h-[400px]">
      
      {/* Table Toolbar */}
      <div className="p-4 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-50/50">
        <div>
          <h2 className="text-lg font-bold text-slate-800">${pageDef.title}</h2>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          ${actionButtons}
        </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-x-auto">
        <table className="w-full text-left text-sm text-slate-600">
          <thead className="bg-[#F8FAFC] text-xs uppercase font-bold text-slate-500 border-b border-slate-200">
            <tr>
              ${tableHeaders}
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {mockData.map((row, i) => (
              <tr key={i} className="hover:bg-primary-50/50 transition-colors group">
                <td className="px-6 py-4 font-bold text-slate-800">{row.id}</td>
                <td className="px-6 py-4 font-medium">{row.col1}</td>
                <td className="px-6 py-4">{row.col2}</td>
                <td className="px-6 py-4 text-slate-500">{row.col3}</td>
                
                {/* Dynamically handle Status Badge vs Normal Column based on pageDef.cols length */}
                {${pageDef.cols.length > 4} ? (
                  <>
                    <td className="px-6 py-4 text-slate-500">{row.col4}</td>
                    <td className="px-6 py-4">
                      <span className={\`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-bold
                        \${row.status === 'Paid' ? 'bg-green-50 text-green-700' : 
                          row.status === 'Pending' ? 'bg-orange-50 text-orange-700' :
                          row.status === 'Overdue' ? 'bg-red-50 text-red-700' :
                          'bg-slate-100 text-slate-700'}
                      \`}>
                        {row.status}
                      </span>
                    </td>
                  </>
                ) : (
                  <td className="px-6 py-4">
                    <span className={\`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-bold
                      \${row.status === 'Paid' ? 'bg-green-50 text-green-700' : 
                        row.status === 'Pending' ? 'bg-orange-50 text-orange-700' :
                        row.status === 'Overdue' ? 'bg-red-50 text-red-700' :
                        'bg-slate-100 text-slate-700'}
                    \`}>
                      {row.status}
                    </span>
                  </td>
                )}

                <td className="px-6 py-4 text-right">
                  <button className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-md transition-colors opacity-0 group-hover:opacity-100 focus:opacity-100">
                    <MoreHorizontal className="w-5 h-5" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      {/* Footer */}
      <div className="p-4 border-t border-slate-200 flex items-center justify-between text-sm text-slate-500 bg-slate-50/50 mt-auto">
        <span>Showing 4 records</span>
        <div className="flex gap-1">
          <button className="px-3 py-1 border border-slate-200 bg-white rounded hover:bg-slate-50 disabled:opacity-50" disabled>Prev</button>
          <button className="px-3 py-1 border border-slate-200 bg-white rounded hover:bg-slate-50 disabled:opacity-50" disabled>Next</button>
        </div>
      </div>

    </div>
  );
}`;
    fs.writeFileSync(path.join(tabPath, 'page.tsx'), code);
  }
}
