"use client";

import React, { useState } from "react";
import { DollarSign, Truck, X, PieChart, BarChart3, Info } from "lucide-react";

interface FleetData {
  id: string;
  registrationNumber: string;
  status: string;
  totalTrips: number;
  totalFuelCost: number;
  totalFuelAmount: number;
}

interface FinancialData {
  income: number;
  expense: number;
  balance: number;
  breakdown: {
    purchaseOrders: number;
    fuelCosts: number;
    pettyCash: number;
  };
}

interface AIReportClientProps {
  data: {
    financial: FinancialData;
    fleet: FleetData[];
  };
}

export default function AIReportClient({ data }: AIReportClientProps) {
  const [showFinModal, setShowFinModal] = useState(false);
  const [showFleetModal, setShowFleetModal] = useState(false);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-KE", {
      style: "currency",
      currency: "KES",
    }).format(amount);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">Comprehensive AI Report</h2>
          <p className="text-slate-400">Holistic summary of school operations, generated by MyShule AI</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Financial Summary Card */}
        <div className="bg-slate-900/50 backdrop-blur-xl p-6 rounded-3xl border border-slate-800">
          <div className="flex items-center gap-4 mb-6">
            <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
              <DollarSign className="w-6 h-6 text-emerald-400" />
            </div>
            <div>
              <h3 className="text-lg font-medium text-white">Financial Health</h3>
              <p className="text-sm text-slate-400">Income vs Expenses</p>
            </div>
          </div>
          
          <div className="space-y-4 mb-6">
            <div className="flex justify-between items-center">
              <span className="text-slate-300">Total Income</span>
              <span className="text-emerald-400 font-semibold">{formatCurrency(data.financial.income)}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-300">Total Expenses</span>
              <span className="text-rose-400 font-semibold">{formatCurrency(data.financial.expense)}</span>
            </div>
            <div className="flex justify-between items-center pt-4 border-t border-slate-800">
              <span className="text-slate-200 font-medium">Net Balance</span>
              <span className={`font-bold ${data.financial.balance >= 0 ? "text-emerald-500" : "text-rose-500"}`}>
                {formatCurrency(data.financial.balance)}
              </span>
            </div>
          </div>

          <button
            onClick={() => setShowFinModal(true)}
            className="w-full py-3 px-4 bg-primary-600 hover:bg-primary-500 text-white rounded-xl transition-colors font-medium flex items-center justify-center gap-2"
          >
            <PieChart className="w-4 h-4" />
            View financial report
          </button>
        </div>

        {/* Fleet Summary Card */}
        <div className="bg-slate-900/50 backdrop-blur-xl p-6 rounded-3xl border border-slate-800">
          <div className="flex items-center gap-4 mb-6">
            <div className="h-12 w-12 rounded-2xl bg-blue-500/10 flex items-center justify-center">
              <Truck className="w-6 h-6 text-blue-400" />
            </div>
            <div>
              <h3 className="text-lg font-medium text-white">Fleet Operations</h3>
              <p className="text-sm text-slate-400">Vehicle usage & fuel tracking</p>
            </div>
          </div>
          
          <div className="space-y-4 mb-6">
            <div className="flex justify-between items-center">
              <span className="text-slate-300">Active Vehicles</span>
              <span className="text-white font-semibold">
                {data.fleet.filter(f => f.status === "ACTIVE").length} / {data.fleet.length}
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-300">Total Fleet Trips</span>
              <span className="text-white font-semibold">
                {data.fleet.reduce((acc, curr) => acc + curr.totalTrips, 0)}
              </span>
            </div>
            <div className="flex justify-between items-center pt-4 border-t border-slate-800">
              <span className="text-slate-200 font-medium">Total Fuel Spent</span>
              <span className="text-rose-400 font-bold">
                {formatCurrency(data.fleet.reduce((acc, curr) => acc + curr.totalFuelCost, 0))}
              </span>
            </div>
          </div>

          <button
            onClick={() => setShowFleetModal(true)}
            className="w-full py-3 px-4 bg-slate-800 hover:bg-slate-700 text-white rounded-xl transition-colors font-medium flex items-center justify-center gap-2 border border-slate-700"
          >
            <BarChart3 className="w-4 h-4" />
            View fleet data
          </button>
        </div>
      </div>

      {/* Financial Modal */}
      {showFinModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-lg overflow-hidden shadow-2xl">
            <div className="p-6 border-b border-slate-800 flex justify-between items-center">
              <h3 className="text-xl font-semibold text-white">Detailed Financial Report</h3>
              <button 
                onClick={() => setShowFinModal(false)}
                className="text-slate-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="p-6 space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-slate-800/50 p-4 rounded-2xl border border-slate-700/50">
                  <p className="text-sm text-slate-400 mb-1">Total Income</p>
                  <p className="text-xl font-semibold text-emerald-400">{formatCurrency(data.financial.income)}</p>
                </div>
                <div className="bg-slate-800/50 p-4 rounded-2xl border border-slate-700/50">
                  <p className="text-sm text-slate-400 mb-1">Total Expenses</p>
                  <p className="text-xl font-semibold text-rose-400">{formatCurrency(data.financial.expense)}</p>
                </div>
              </div>
              
              <div>
                <h4 className="text-sm font-medium text-slate-300 mb-3 uppercase tracking-wider">Expense Breakdown</h4>
                <div className="space-y-3">
                  <div className="flex justify-between items-center bg-slate-800/30 p-3 rounded-xl border border-slate-700/30">
                    <span className="text-slate-300 text-sm">Purchase Orders</span>
                    <span className="text-slate-200 font-medium">{formatCurrency(data.financial.breakdown.purchaseOrders)}</span>
                  </div>
                  <div className="flex justify-between items-center bg-slate-800/30 p-3 rounded-xl border border-slate-700/30">
                    <span className="text-slate-300 text-sm">Fleet Fuel Costs</span>
                    <span className="text-slate-200 font-medium">{formatCurrency(data.financial.breakdown.fuelCosts)}</span>
                  </div>
                  <div className="flex justify-between items-center bg-slate-800/30 p-3 rounded-xl border border-slate-700/30">
                    <span className="text-slate-300 text-sm">Petty Cash Outflows</span>
                    <span className="text-slate-200 font-medium">{formatCurrency(data.financial.breakdown.pettyCash)}</span>
                  </div>
                </div>
              </div>

              <div className="bg-blue-500/10 border border-blue-500/20 p-4 rounded-2xl flex gap-3">
                <Info className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
                <p className="text-sm text-blue-300 leading-relaxed">
                  The AI identifies that {data.financial.expense > 0 ? ((data.financial.breakdown.purchaseOrders / data.financial.expense) * 100).toFixed(1) : 0}% of your expenses are driven by purchase orders. Consider negotiating better terms with suppliers to improve net balance.
                </p>
              </div>
            </div>
            <div className="p-4 border-t border-slate-800 bg-slate-900/50 flex justify-end">
              <button
                onClick={() => {
                  window.print();
                }}
                className="py-2 px-4 bg-primary-600 hover:bg-primary-500 text-white rounded-xl transition-colors font-medium text-sm"
              >
                Export to PDF
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Fleet Modal */}
      {showFleetModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[85vh]">
            <div className="p-6 border-b border-slate-800 flex justify-between items-center shrink-0">
              <h3 className="text-xl font-semibold text-white">Detailed Fleet Data</h3>
              <button 
                onClick={() => setShowFleetModal(false)}
                className="text-slate-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto">
              <div className="space-y-4">
                {data.fleet.length > 0 ? (
                  data.fleet.map((vehicle) => (
                    <div key={vehicle.id} className="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-4">
                      <div className="flex justify-between items-start mb-3">
                        <div>
                          <div className="flex items-center gap-2">
                            <h4 className="text-lg font-semibold text-white">{vehicle.registrationNumber}</h4>
                            <span className={`px-2 py-0.5 text-xs rounded-full font-medium ${
                              vehicle.status === "ACTIVE" ? "bg-emerald-500/10 text-emerald-400" :
                              vehicle.status === "MAINTENANCE" ? "bg-amber-500/10 text-amber-400" :
                              "bg-slate-500/10 text-slate-400"
                            }`}>
                              {vehicle.status}
                            </span>
                          </div>
                          <p className="text-sm text-slate-400">Total Trips: {vehicle.totalTrips}</p>
                        </div>
                        <div className="text-right">
                          <p className="text-sm text-slate-400">Fuel Cost</p>
                          <p className="text-white font-medium">{formatCurrency(vehicle.totalFuelCost)}</p>
                        </div>
                      </div>
                      <div className="flex items-center justify-between text-sm pt-3 border-t border-slate-700/50">
                        <span className="text-slate-400">Fuel Amount: {vehicle.totalFuelAmount} Liters</span>
                        {vehicle.totalTrips > 0 && vehicle.totalFuelAmount > 0 && (
                          <span className="text-blue-400">
                            Avg {(vehicle.totalFuelCost / vehicle.totalTrips).toFixed(2)} KES/Trip
                          </span>
                        )}
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-8 text-slate-400">
                    No vehicles found in the fleet.
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
